version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Giridharan@31
      MYSQL_DATABASE: todo_application
    ports:
      - "3306:3306"
    networks:
      - todo-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_application
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Giridharan@31
    depends_on:
      - db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
