version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: A2xHU9xPV2
      MYSQL_DATABASE: sql12709583
    ports:
      - "3306:3306"
    networks:
      - todo-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12709583
      SPRING_DATASOURCE_USERNAME: sql12709583
      SPRING_DATASOURCE_PASSWORD: A2xHU9xPV2
    depends_on:
      - db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
